// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tendermint.proto

package types

import (
	fmt "fmt"
	types "github.com/33cn/chain33/types"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockID struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockID) Reset()         { *m = BlockID{} }
func (m *BlockID) String() string { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()    {}
func (*BlockID) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{0}
}

func (m *BlockID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockID.Unmarshal(m, b)
}
func (m *BlockID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockID.Marshal(b, m, deterministic)
}
func (m *BlockID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockID.Merge(m, src)
}
func (m *BlockID) XXX_Size() int {
	return xxx_messageInfo_BlockID.Size(m)
}
func (m *BlockID) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockID.DiscardUnknown(m)
}

var xxx_messageInfo_BlockID proto.InternalMessageInfo

func (m *BlockID) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type TendermintBitArray struct {
	Bits                 int32    `protobuf:"varint,1,opt,name=bits,proto3" json:"bits,omitempty"`
	Elems                []uint64 `protobuf:"varint,2,rep,packed,name=elems,proto3" json:"elems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TendermintBitArray) Reset()         { *m = TendermintBitArray{} }
func (m *TendermintBitArray) String() string { return proto.CompactTextString(m) }
func (*TendermintBitArray) ProtoMessage()    {}
func (*TendermintBitArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{1}
}

func (m *TendermintBitArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintBitArray.Unmarshal(m, b)
}
func (m *TendermintBitArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintBitArray.Marshal(b, m, deterministic)
}
func (m *TendermintBitArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintBitArray.Merge(m, src)
}
func (m *TendermintBitArray) XXX_Size() int {
	return xxx_messageInfo_TendermintBitArray.Size(m)
}
func (m *TendermintBitArray) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintBitArray.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintBitArray proto.InternalMessageInfo

func (m *TendermintBitArray) GetBits() int32 {
	if m != nil {
		return m.Bits
	}
	return 0
}

func (m *TendermintBitArray) GetElems() []uint64 {
	if m != nil {
		return m.Elems
	}
	return nil
}

type Vote struct {
	ValidatorAddress     []byte   `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	ValidatorIndex       int32    `protobuf:"varint,2,opt,name=validatorIndex,proto3" json:"validatorIndex,omitempty"`
	Height               int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 uint32   `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	BlockID              *BlockID `protobuf:"bytes,7,opt,name=blockID,proto3" json:"blockID,omitempty"`
	Signature            []byte   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	UseAggSig            bool     `protobuf:"varint,9,opt,name=useAggSig,proto3" json:"useAggSig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{2}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetValidatorAddress() []byte {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *Vote) GetValidatorIndex() int32 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

func (m *Vote) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Vote) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Vote) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Vote) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Vote) GetBlockID() *BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

func (m *Vote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Vote) GetUseAggSig() bool {
	if m != nil {
		return m.UseAggSig
	}
	return false
}

type TendermintCommit struct {
	BlockID              *BlockID `protobuf:"bytes,1,opt,name=blockID,proto3" json:"blockID,omitempty"`
	Precommits           []*Vote  `protobuf:"bytes,2,rep,name=precommits,proto3" json:"precommits,omitempty"`
	AggVote              *AggVote `protobuf:"bytes,3,opt,name=aggVote,proto3" json:"aggVote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TendermintCommit) Reset()         { *m = TendermintCommit{} }
func (m *TendermintCommit) String() string { return proto.CompactTextString(m) }
func (*TendermintCommit) ProtoMessage()    {}
func (*TendermintCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{3}
}

func (m *TendermintCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintCommit.Unmarshal(m, b)
}
func (m *TendermintCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintCommit.Marshal(b, m, deterministic)
}
func (m *TendermintCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintCommit.Merge(m, src)
}
func (m *TendermintCommit) XXX_Size() int {
	return xxx_messageInfo_TendermintCommit.Size(m)
}
func (m *TendermintCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintCommit.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintCommit proto.InternalMessageInfo

func (m *TendermintCommit) GetBlockID() *BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

func (m *TendermintCommit) GetPrecommits() []*Vote {
	if m != nil {
		return m.Precommits
	}
	return nil
}

func (m *TendermintCommit) GetAggVote() *AggVote {
	if m != nil {
		return m.AggVote
	}
	return nil
}

type TendermintBlockInfo struct {
	State                *State           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Proposal             *Proposal        `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Block                *TendermintBlock `protobuf:"bytes,4,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TendermintBlockInfo) Reset()         { *m = TendermintBlockInfo{} }
func (m *TendermintBlockInfo) String() string { return proto.CompactTextString(m) }
func (*TendermintBlockInfo) ProtoMessage()    {}
func (*TendermintBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{4}
}

func (m *TendermintBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintBlockInfo.Unmarshal(m, b)
}
func (m *TendermintBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintBlockInfo.Marshal(b, m, deterministic)
}
func (m *TendermintBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintBlockInfo.Merge(m, src)
}
func (m *TendermintBlockInfo) XXX_Size() int {
	return xxx_messageInfo_TendermintBlockInfo.Size(m)
}
func (m *TendermintBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintBlockInfo proto.InternalMessageInfo

func (m *TendermintBlockInfo) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *TendermintBlockInfo) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *TendermintBlockInfo) GetBlock() *TendermintBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type BlockSize struct {
	MaxBytes             int32    `protobuf:"varint,1,opt,name=maxBytes,proto3" json:"maxBytes,omitempty"`
	MaxTxs               int32    `protobuf:"varint,2,opt,name=maxTxs,proto3" json:"maxTxs,omitempty"`
	MaxGas               int64    `protobuf:"varint,3,opt,name=maxGas,proto3" json:"maxGas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSize) Reset()         { *m = BlockSize{} }
func (m *BlockSize) String() string { return proto.CompactTextString(m) }
func (*BlockSize) ProtoMessage()    {}
func (*BlockSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{5}
}

func (m *BlockSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSize.Unmarshal(m, b)
}
func (m *BlockSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSize.Marshal(b, m, deterministic)
}
func (m *BlockSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSize.Merge(m, src)
}
func (m *BlockSize) XXX_Size() int {
	return xxx_messageInfo_BlockSize.Size(m)
}
func (m *BlockSize) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSize.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSize proto.InternalMessageInfo

func (m *BlockSize) GetMaxBytes() int32 {
	if m != nil {
		return m.MaxBytes
	}
	return 0
}

func (m *BlockSize) GetMaxTxs() int32 {
	if m != nil {
		return m.MaxTxs
	}
	return 0
}

func (m *BlockSize) GetMaxGas() int64 {
	if m != nil {
		return m.MaxGas
	}
	return 0
}

type TxSize struct {
	MaxBytes             int32    `protobuf:"varint,1,opt,name=maxBytes,proto3" json:"maxBytes,omitempty"`
	MaxGas               int64    `protobuf:"varint,2,opt,name=maxGas,proto3" json:"maxGas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxSize) Reset()         { *m = TxSize{} }
func (m *TxSize) String() string { return proto.CompactTextString(m) }
func (*TxSize) ProtoMessage()    {}
func (*TxSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{6}
}

func (m *TxSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxSize.Unmarshal(m, b)
}
func (m *TxSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxSize.Marshal(b, m, deterministic)
}
func (m *TxSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxSize.Merge(m, src)
}
func (m *TxSize) XXX_Size() int {
	return xxx_messageInfo_TxSize.Size(m)
}
func (m *TxSize) XXX_DiscardUnknown() {
	xxx_messageInfo_TxSize.DiscardUnknown(m)
}

var xxx_messageInfo_TxSize proto.InternalMessageInfo

func (m *TxSize) GetMaxBytes() int32 {
	if m != nil {
		return m.MaxBytes
	}
	return 0
}

func (m *TxSize) GetMaxGas() int64 {
	if m != nil {
		return m.MaxGas
	}
	return 0
}

type BlockGossip struct {
	BlockPartSizeBytes   int32    `protobuf:"varint,1,opt,name=blockPartSizeBytes,proto3" json:"blockPartSizeBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockGossip) Reset()         { *m = BlockGossip{} }
func (m *BlockGossip) String() string { return proto.CompactTextString(m) }
func (*BlockGossip) ProtoMessage()    {}
func (*BlockGossip) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{7}
}

func (m *BlockGossip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockGossip.Unmarshal(m, b)
}
func (m *BlockGossip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockGossip.Marshal(b, m, deterministic)
}
func (m *BlockGossip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockGossip.Merge(m, src)
}
func (m *BlockGossip) XXX_Size() int {
	return xxx_messageInfo_BlockGossip.Size(m)
}
func (m *BlockGossip) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockGossip.DiscardUnknown(m)
}

var xxx_messageInfo_BlockGossip proto.InternalMessageInfo

func (m *BlockGossip) GetBlockPartSizeBytes() int32 {
	if m != nil {
		return m.BlockPartSizeBytes
	}
	return 0
}

type EvidenceParams struct {
	MaxAge               int64    `protobuf:"varint,1,opt,name=maxAge,proto3" json:"maxAge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvidenceParams) Reset()         { *m = EvidenceParams{} }
func (m *EvidenceParams) String() string { return proto.CompactTextString(m) }
func (*EvidenceParams) ProtoMessage()    {}
func (*EvidenceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{8}
}

func (m *EvidenceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvidenceParams.Unmarshal(m, b)
}
func (m *EvidenceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvidenceParams.Marshal(b, m, deterministic)
}
func (m *EvidenceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvidenceParams.Merge(m, src)
}
func (m *EvidenceParams) XXX_Size() int {
	return xxx_messageInfo_EvidenceParams.Size(m)
}
func (m *EvidenceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EvidenceParams.DiscardUnknown(m)
}

var xxx_messageInfo_EvidenceParams proto.InternalMessageInfo

func (m *EvidenceParams) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

type ConsensusParams struct {
	BlockSize            *BlockSize      `protobuf:"bytes,1,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	TxSize               *TxSize         `protobuf:"bytes,2,opt,name=txSize,proto3" json:"txSize,omitempty"`
	BlockGossip          *BlockGossip    `protobuf:"bytes,3,opt,name=blockGossip,proto3" json:"blockGossip,omitempty"`
	EvidenceParams       *EvidenceParams `protobuf:"bytes,4,opt,name=evidenceParams,proto3" json:"evidenceParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConsensusParams) Reset()         { *m = ConsensusParams{} }
func (m *ConsensusParams) String() string { return proto.CompactTextString(m) }
func (*ConsensusParams) ProtoMessage()    {}
func (*ConsensusParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{9}
}

func (m *ConsensusParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusParams.Unmarshal(m, b)
}
func (m *ConsensusParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusParams.Marshal(b, m, deterministic)
}
func (m *ConsensusParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusParams.Merge(m, src)
}
func (m *ConsensusParams) XXX_Size() int {
	return xxx_messageInfo_ConsensusParams.Size(m)
}
func (m *ConsensusParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusParams.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusParams proto.InternalMessageInfo

func (m *ConsensusParams) GetBlockSize() *BlockSize {
	if m != nil {
		return m.BlockSize
	}
	return nil
}

func (m *ConsensusParams) GetTxSize() *TxSize {
	if m != nil {
		return m.TxSize
	}
	return nil
}

func (m *ConsensusParams) GetBlockGossip() *BlockGossip {
	if m != nil {
		return m.BlockGossip
	}
	return nil
}

func (m *ConsensusParams) GetEvidenceParams() *EvidenceParams {
	if m != nil {
		return m.EvidenceParams
	}
	return nil
}

type Validator struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	VotingPower          int64    `protobuf:"varint,3,opt,name=votingPower,proto3" json:"votingPower,omitempty"`
	Accum                int64    `protobuf:"varint,4,opt,name=accum,proto3" json:"accum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{10}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Validator) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Validator) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *Validator) GetAccum() int64 {
	if m != nil {
		return m.Accum
	}
	return 0
}

type ValidatorSet struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	Proposer             *Validator   `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ValidatorSet) Reset()         { *m = ValidatorSet{} }
func (m *ValidatorSet) String() string { return proto.CompactTextString(m) }
func (*ValidatorSet) ProtoMessage()    {}
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{11}
}

func (m *ValidatorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorSet.Unmarshal(m, b)
}
func (m *ValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorSet.Marshal(b, m, deterministic)
}
func (m *ValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSet.Merge(m, src)
}
func (m *ValidatorSet) XXX_Size() int {
	return xxx_messageInfo_ValidatorSet.Size(m)
}
func (m *ValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSet proto.InternalMessageInfo

func (m *ValidatorSet) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *ValidatorSet) GetProposer() *Validator {
	if m != nil {
		return m.Proposer
	}
	return nil
}

type State struct {
	ChainID                          string           `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	LastHeight                       int64            `protobuf:"varint,2,opt,name=lastHeight,proto3" json:"lastHeight,omitempty"`
	LastBlockHeight                  int64            `protobuf:"varint,3,opt,name=lastBlockHeight,proto3" json:"lastBlockHeight,omitempty"`
	LastBlockTotalTx                 int64            `protobuf:"varint,4,opt,name=lastBlockTotalTx,proto3" json:"lastBlockTotalTx,omitempty"`
	LastBlockID                      *BlockID         `protobuf:"bytes,5,opt,name=lastBlockID,proto3" json:"lastBlockID,omitempty"`
	LastBlockTime                    int64            `protobuf:"varint,6,opt,name=lastBlockTime,proto3" json:"lastBlockTime,omitempty"`
	Validators                       *ValidatorSet    `protobuf:"bytes,7,opt,name=validators,proto3" json:"validators,omitempty"`
	LastValidators                   *ValidatorSet    `protobuf:"bytes,8,opt,name=lastValidators,proto3" json:"lastValidators,omitempty"`
	LastHeightValidatorsChanged      int64            `protobuf:"varint,9,opt,name=lastHeightValidatorsChanged,proto3" json:"lastHeightValidatorsChanged,omitempty"`
	ConsensusParams                  *ConsensusParams `protobuf:"bytes,10,opt,name=consensusParams,proto3" json:"consensusParams,omitempty"`
	LastHeightConsensusParamsChanged int64            `protobuf:"varint,11,opt,name=lastHeightConsensusParamsChanged,proto3" json:"lastHeightConsensusParamsChanged,omitempty"`
	LastResultsHash                  []byte           `protobuf:"bytes,12,opt,name=lastResultsHash,proto3" json:"lastResultsHash,omitempty"`
	AppHash                          []byte           `protobuf:"bytes,13,opt,name=appHash,proto3" json:"appHash,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}         `json:"-"`
	XXX_unrecognized                 []byte           `json:"-"`
	XXX_sizecache                    int32            `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{12}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *State) GetLastHeight() int64 {
	if m != nil {
		return m.LastHeight
	}
	return 0
}

func (m *State) GetLastBlockHeight() int64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *State) GetLastBlockTotalTx() int64 {
	if m != nil {
		return m.LastBlockTotalTx
	}
	return 0
}

func (m *State) GetLastBlockID() *BlockID {
	if m != nil {
		return m.LastBlockID
	}
	return nil
}

func (m *State) GetLastBlockTime() int64 {
	if m != nil {
		return m.LastBlockTime
	}
	return 0
}

func (m *State) GetValidators() *ValidatorSet {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *State) GetLastValidators() *ValidatorSet {
	if m != nil {
		return m.LastValidators
	}
	return nil
}

func (m *State) GetLastHeightValidatorsChanged() int64 {
	if m != nil {
		return m.LastHeightValidatorsChanged
	}
	return 0
}

func (m *State) GetConsensusParams() *ConsensusParams {
	if m != nil {
		return m.ConsensusParams
	}
	return nil
}

func (m *State) GetLastHeightConsensusParamsChanged() int64 {
	if m != nil {
		return m.LastHeightConsensusParamsChanged
	}
	return 0
}

func (m *State) GetLastResultsHash() []byte {
	if m != nil {
		return m.LastResultsHash
	}
	return nil
}

func (m *State) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

type TendermintBlockHeader struct {
	ChainID              string   `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                int64    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	NumTxs               int64    `protobuf:"varint,5,opt,name=numTxs,proto3" json:"numTxs,omitempty"`
	LastBlockID          *BlockID `protobuf:"bytes,6,opt,name=lastBlockID,proto3" json:"lastBlockID,omitempty"`
	TotalTxs             int64    `protobuf:"varint,7,opt,name=totalTxs,proto3" json:"totalTxs,omitempty"`
	LastCommitHash       []byte   `protobuf:"bytes,8,opt,name=lastCommitHash,proto3" json:"lastCommitHash,omitempty"`
	ValidatorsHash       []byte   `protobuf:"bytes,9,opt,name=validatorsHash,proto3" json:"validatorsHash,omitempty"`
	ConsensusHash        []byte   `protobuf:"bytes,10,opt,name=consensusHash,proto3" json:"consensusHash,omitempty"`
	AppHash              []byte   `protobuf:"bytes,11,opt,name=appHash,proto3" json:"appHash,omitempty"`
	LastResultsHash      []byte   `protobuf:"bytes,12,opt,name=lastResultsHash,proto3" json:"lastResultsHash,omitempty"`
	ProposerAddr         []byte   `protobuf:"bytes,13,opt,name=proposerAddr,proto3" json:"proposerAddr,omitempty"`
	BlockHeight          int64    `protobuf:"varint,14,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	BlockSequence        int64    `protobuf:"varint,15,opt,name=blockSequence,proto3" json:"blockSequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TendermintBlockHeader) Reset()         { *m = TendermintBlockHeader{} }
func (m *TendermintBlockHeader) String() string { return proto.CompactTextString(m) }
func (*TendermintBlockHeader) ProtoMessage()    {}
func (*TendermintBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{13}
}

func (m *TendermintBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintBlockHeader.Unmarshal(m, b)
}
func (m *TendermintBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintBlockHeader.Marshal(b, m, deterministic)
}
func (m *TendermintBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintBlockHeader.Merge(m, src)
}
func (m *TendermintBlockHeader) XXX_Size() int {
	return xxx_messageInfo_TendermintBlockHeader.Size(m)
}
func (m *TendermintBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintBlockHeader proto.InternalMessageInfo

func (m *TendermintBlockHeader) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *TendermintBlockHeader) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TendermintBlockHeader) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *TendermintBlockHeader) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TendermintBlockHeader) GetNumTxs() int64 {
	if m != nil {
		return m.NumTxs
	}
	return 0
}

func (m *TendermintBlockHeader) GetLastBlockID() *BlockID {
	if m != nil {
		return m.LastBlockID
	}
	return nil
}

func (m *TendermintBlockHeader) GetTotalTxs() int64 {
	if m != nil {
		return m.TotalTxs
	}
	return 0
}

func (m *TendermintBlockHeader) GetLastCommitHash() []byte {
	if m != nil {
		return m.LastCommitHash
	}
	return nil
}

func (m *TendermintBlockHeader) GetValidatorsHash() []byte {
	if m != nil {
		return m.ValidatorsHash
	}
	return nil
}

func (m *TendermintBlockHeader) GetConsensusHash() []byte {
	if m != nil {
		return m.ConsensusHash
	}
	return nil
}

func (m *TendermintBlockHeader) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

func (m *TendermintBlockHeader) GetLastResultsHash() []byte {
	if m != nil {
		return m.LastResultsHash
	}
	return nil
}

func (m *TendermintBlockHeader) GetProposerAddr() []byte {
	if m != nil {
		return m.ProposerAddr
	}
	return nil
}

func (m *TendermintBlockHeader) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *TendermintBlockHeader) GetBlockSequence() int64 {
	if m != nil {
		return m.BlockSequence
	}
	return 0
}

type TendermintBlock struct {
	Header               *TendermintBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *types.Block           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	LastCommit           *TendermintCommit      `protobuf:"bytes,4,opt,name=lastCommit,proto3" json:"lastCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TendermintBlock) Reset()         { *m = TendermintBlock{} }
func (m *TendermintBlock) String() string { return proto.CompactTextString(m) }
func (*TendermintBlock) ProtoMessage()    {}
func (*TendermintBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{14}
}

func (m *TendermintBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintBlock.Unmarshal(m, b)
}
func (m *TendermintBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintBlock.Marshal(b, m, deterministic)
}
func (m *TendermintBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintBlock.Merge(m, src)
}
func (m *TendermintBlock) XXX_Size() int {
	return xxx_messageInfo_TendermintBlock.Size(m)
}
func (m *TendermintBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintBlock.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintBlock proto.InternalMessageInfo

func (m *TendermintBlock) GetHeader() *TendermintBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TendermintBlock) GetData() *types.Block {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TendermintBlock) GetLastCommit() *TendermintCommit {
	if m != nil {
		return m.LastCommit
	}
	return nil
}

type Proposal struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	POLRound             int32    `protobuf:"varint,4,opt,name=POLRound,proto3" json:"POLRound,omitempty"`
	POLBlockID           *BlockID `protobuf:"bytes,5,opt,name=POLBlockID,proto3" json:"POLBlockID,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Blockhash            []byte   `protobuf:"bytes,7,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	BlockHeight          int64    `protobuf:"varint,8,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{15}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Proposal) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Proposal) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Proposal) GetPOLRound() int32 {
	if m != nil {
		return m.POLRound
	}
	return 0
}

func (m *Proposal) GetPOLBlockID() *BlockID {
	if m != nil {
		return m.POLBlockID
	}
	return nil
}

func (m *Proposal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Proposal) GetBlockhash() []byte {
	if m != nil {
		return m.Blockhash
	}
	return nil
}

func (m *Proposal) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type NewRoundStepMsg struct {
	Height                int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                 int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step                  int32    `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	SecondsSinceStartTime int32    `protobuf:"varint,4,opt,name=secondsSinceStartTime,proto3" json:"secondsSinceStartTime,omitempty"`
	LastCommitRound       int32    `protobuf:"varint,5,opt,name=lastCommitRound,proto3" json:"lastCommitRound,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *NewRoundStepMsg) Reset()         { *m = NewRoundStepMsg{} }
func (m *NewRoundStepMsg) String() string { return proto.CompactTextString(m) }
func (*NewRoundStepMsg) ProtoMessage()    {}
func (*NewRoundStepMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{16}
}

func (m *NewRoundStepMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRoundStepMsg.Unmarshal(m, b)
}
func (m *NewRoundStepMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRoundStepMsg.Marshal(b, m, deterministic)
}
func (m *NewRoundStepMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRoundStepMsg.Merge(m, src)
}
func (m *NewRoundStepMsg) XXX_Size() int {
	return xxx_messageInfo_NewRoundStepMsg.Size(m)
}
func (m *NewRoundStepMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRoundStepMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NewRoundStepMsg proto.InternalMessageInfo

func (m *NewRoundStepMsg) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NewRoundStepMsg) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *NewRoundStepMsg) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *NewRoundStepMsg) GetSecondsSinceStartTime() int32 {
	if m != nil {
		return m.SecondsSinceStartTime
	}
	return 0
}

func (m *NewRoundStepMsg) GetLastCommitRound() int32 {
	if m != nil {
		return m.LastCommitRound
	}
	return 0
}

type ValidBlockMsg struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Blockhash            []byte   `protobuf:"bytes,3,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	IsCommit             bool     `protobuf:"varint,4,opt,name=isCommit,proto3" json:"isCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidBlockMsg) Reset()         { *m = ValidBlockMsg{} }
func (m *ValidBlockMsg) String() string { return proto.CompactTextString(m) }
func (*ValidBlockMsg) ProtoMessage()    {}
func (*ValidBlockMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{17}
}

func (m *ValidBlockMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidBlockMsg.Unmarshal(m, b)
}
func (m *ValidBlockMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidBlockMsg.Marshal(b, m, deterministic)
}
func (m *ValidBlockMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidBlockMsg.Merge(m, src)
}
func (m *ValidBlockMsg) XXX_Size() int {
	return xxx_messageInfo_ValidBlockMsg.Size(m)
}
func (m *ValidBlockMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidBlockMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ValidBlockMsg proto.InternalMessageInfo

func (m *ValidBlockMsg) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ValidBlockMsg) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ValidBlockMsg) GetBlockhash() []byte {
	if m != nil {
		return m.Blockhash
	}
	return nil
}

func (m *ValidBlockMsg) GetIsCommit() bool {
	if m != nil {
		return m.IsCommit
	}
	return false
}

type ProposalPOLMsg struct {
	Height               int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	ProposalPOLRound     int32               `protobuf:"varint,2,opt,name=proposalPOLRound,proto3" json:"proposalPOLRound,omitempty"`
	ProposalPOL          *TendermintBitArray `protobuf:"bytes,3,opt,name=proposalPOL,proto3" json:"proposalPOL,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProposalPOLMsg) Reset()         { *m = ProposalPOLMsg{} }
func (m *ProposalPOLMsg) String() string { return proto.CompactTextString(m) }
func (*ProposalPOLMsg) ProtoMessage()    {}
func (*ProposalPOLMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{18}
}

func (m *ProposalPOLMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalPOLMsg.Unmarshal(m, b)
}
func (m *ProposalPOLMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalPOLMsg.Marshal(b, m, deterministic)
}
func (m *ProposalPOLMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalPOLMsg.Merge(m, src)
}
func (m *ProposalPOLMsg) XXX_Size() int {
	return xxx_messageInfo_ProposalPOLMsg.Size(m)
}
func (m *ProposalPOLMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalPOLMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalPOLMsg proto.InternalMessageInfo

func (m *ProposalPOLMsg) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProposalPOLMsg) GetProposalPOLRound() int32 {
	if m != nil {
		return m.ProposalPOLRound
	}
	return 0
}

func (m *ProposalPOLMsg) GetProposalPOL() *TendermintBitArray {
	if m != nil {
		return m.ProposalPOL
	}
	return nil
}

type HasVoteMsg struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Index                int32    `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasVoteMsg) Reset()         { *m = HasVoteMsg{} }
func (m *HasVoteMsg) String() string { return proto.CompactTextString(m) }
func (*HasVoteMsg) ProtoMessage()    {}
func (*HasVoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{19}
}

func (m *HasVoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasVoteMsg.Unmarshal(m, b)
}
func (m *HasVoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasVoteMsg.Marshal(b, m, deterministic)
}
func (m *HasVoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasVoteMsg.Merge(m, src)
}
func (m *HasVoteMsg) XXX_Size() int {
	return xxx_messageInfo_HasVoteMsg.Size(m)
}
func (m *HasVoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HasVoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HasVoteMsg proto.InternalMessageInfo

func (m *HasVoteMsg) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HasVoteMsg) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *HasVoteMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *HasVoteMsg) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type VoteSetMaj23Msg struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	BlockID              *BlockID `protobuf:"bytes,4,opt,name=blockID,proto3" json:"blockID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteSetMaj23Msg) Reset()         { *m = VoteSetMaj23Msg{} }
func (m *VoteSetMaj23Msg) String() string { return proto.CompactTextString(m) }
func (*VoteSetMaj23Msg) ProtoMessage()    {}
func (*VoteSetMaj23Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{20}
}

func (m *VoteSetMaj23Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteSetMaj23Msg.Unmarshal(m, b)
}
func (m *VoteSetMaj23Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteSetMaj23Msg.Marshal(b, m, deterministic)
}
func (m *VoteSetMaj23Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteSetMaj23Msg.Merge(m, src)
}
func (m *VoteSetMaj23Msg) XXX_Size() int {
	return xxx_messageInfo_VoteSetMaj23Msg.Size(m)
}
func (m *VoteSetMaj23Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteSetMaj23Msg.DiscardUnknown(m)
}

var xxx_messageInfo_VoteSetMaj23Msg proto.InternalMessageInfo

func (m *VoteSetMaj23Msg) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VoteSetMaj23Msg) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *VoteSetMaj23Msg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *VoteSetMaj23Msg) GetBlockID() *BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

type VoteSetBitsMsg struct {
	Height               int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type                 int32               `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	BlockID              *BlockID            `protobuf:"bytes,4,opt,name=blockID,proto3" json:"blockID,omitempty"`
	Votes                *TendermintBitArray `protobuf:"bytes,5,opt,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VoteSetBitsMsg) Reset()         { *m = VoteSetBitsMsg{} }
func (m *VoteSetBitsMsg) String() string { return proto.CompactTextString(m) }
func (*VoteSetBitsMsg) ProtoMessage()    {}
func (*VoteSetBitsMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{21}
}

func (m *VoteSetBitsMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteSetBitsMsg.Unmarshal(m, b)
}
func (m *VoteSetBitsMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteSetBitsMsg.Marshal(b, m, deterministic)
}
func (m *VoteSetBitsMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteSetBitsMsg.Merge(m, src)
}
func (m *VoteSetBitsMsg) XXX_Size() int {
	return xxx_messageInfo_VoteSetBitsMsg.Size(m)
}
func (m *VoteSetBitsMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteSetBitsMsg.DiscardUnknown(m)
}

var xxx_messageInfo_VoteSetBitsMsg proto.InternalMessageInfo

func (m *VoteSetBitsMsg) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VoteSetBitsMsg) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *VoteSetBitsMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *VoteSetBitsMsg) GetBlockID() *BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

func (m *VoteSetBitsMsg) GetVotes() *TendermintBitArray {
	if m != nil {
		return m.Votes
	}
	return nil
}

type Heartbeat struct {
	ValidatorAddress     []byte   `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	ValidatorIndex       int32    `protobuf:"varint,2,opt,name=validatorIndex,proto3" json:"validatorIndex,omitempty"`
	Height               int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Sequence             int32    `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{22}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetValidatorAddress() []byte {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *Heartbeat) GetValidatorIndex() int32 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

func (m *Heartbeat) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Heartbeat) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Heartbeat) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Heartbeat) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type IsHealthy struct {
	IsHealthy            bool     `protobuf:"varint,1,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsHealthy) Reset()         { *m = IsHealthy{} }
func (m *IsHealthy) String() string { return proto.CompactTextString(m) }
func (*IsHealthy) ProtoMessage()    {}
func (*IsHealthy) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{23}
}

func (m *IsHealthy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsHealthy.Unmarshal(m, b)
}
func (m *IsHealthy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsHealthy.Marshal(b, m, deterministic)
}
func (m *IsHealthy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsHealthy.Merge(m, src)
}
func (m *IsHealthy) XXX_Size() int {
	return xxx_messageInfo_IsHealthy.Size(m)
}
func (m *IsHealthy) XXX_DiscardUnknown() {
	xxx_messageInfo_IsHealthy.DiscardUnknown(m)
}

var xxx_messageInfo_IsHealthy proto.InternalMessageInfo

func (m *IsHealthy) GetIsHealthy() bool {
	if m != nil {
		return m.IsHealthy
	}
	return false
}

type AggVote struct {
	ValidatorAddress     []byte              `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	ValidatorArray       *TendermintBitArray `protobuf:"bytes,2,opt,name=validatorArray,proto3" json:"validatorArray,omitempty"`
	Height               int64               `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32               `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp            int64               `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 uint32              `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	BlockID              *BlockID            `protobuf:"bytes,7,opt,name=blockID,proto3" json:"blockID,omitempty"`
	Signature            []byte              `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AggVote) Reset()         { *m = AggVote{} }
func (m *AggVote) String() string { return proto.CompactTextString(m) }
func (*AggVote) ProtoMessage()    {}
func (*AggVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_04f926c8da23c367, []int{24}
}

func (m *AggVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggVote.Unmarshal(m, b)
}
func (m *AggVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggVote.Marshal(b, m, deterministic)
}
func (m *AggVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggVote.Merge(m, src)
}
func (m *AggVote) XXX_Size() int {
	return xxx_messageInfo_AggVote.Size(m)
}
func (m *AggVote) XXX_DiscardUnknown() {
	xxx_messageInfo_AggVote.DiscardUnknown(m)
}

var xxx_messageInfo_AggVote proto.InternalMessageInfo

func (m *AggVote) GetValidatorAddress() []byte {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *AggVote) GetValidatorArray() *TendermintBitArray {
	if m != nil {
		return m.ValidatorArray
	}
	return nil
}

func (m *AggVote) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AggVote) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *AggVote) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AggVote) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AggVote) GetBlockID() *BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

func (m *AggVote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockID)(nil), "types.BlockID")
	proto.RegisterType((*TendermintBitArray)(nil), "types.TendermintBitArray")
	proto.RegisterType((*Vote)(nil), "types.Vote")
	proto.RegisterType((*TendermintCommit)(nil), "types.TendermintCommit")
	proto.RegisterType((*TendermintBlockInfo)(nil), "types.TendermintBlockInfo")
	proto.RegisterType((*BlockSize)(nil), "types.BlockSize")
	proto.RegisterType((*TxSize)(nil), "types.TxSize")
	proto.RegisterType((*BlockGossip)(nil), "types.BlockGossip")
	proto.RegisterType((*EvidenceParams)(nil), "types.EvidenceParams")
	proto.RegisterType((*ConsensusParams)(nil), "types.ConsensusParams")
	proto.RegisterType((*Validator)(nil), "types.Validator")
	proto.RegisterType((*ValidatorSet)(nil), "types.ValidatorSet")
	proto.RegisterType((*State)(nil), "types.State")
	proto.RegisterType((*TendermintBlockHeader)(nil), "types.TendermintBlockHeader")
	proto.RegisterType((*TendermintBlock)(nil), "types.TendermintBlock")
	proto.RegisterType((*Proposal)(nil), "types.Proposal")
	proto.RegisterType((*NewRoundStepMsg)(nil), "types.NewRoundStepMsg")
	proto.RegisterType((*ValidBlockMsg)(nil), "types.ValidBlockMsg")
	proto.RegisterType((*ProposalPOLMsg)(nil), "types.ProposalPOLMsg")
	proto.RegisterType((*HasVoteMsg)(nil), "types.HasVoteMsg")
	proto.RegisterType((*VoteSetMaj23Msg)(nil), "types.VoteSetMaj23Msg")
	proto.RegisterType((*VoteSetBitsMsg)(nil), "types.VoteSetBitsMsg")
	proto.RegisterType((*Heartbeat)(nil), "types.Heartbeat")
	proto.RegisterType((*IsHealthy)(nil), "types.IsHealthy")
	proto.RegisterType((*AggVote)(nil), "types.AggVote")
}

func init() { proto.RegisterFile("tendermint.proto", fileDescriptor_04f926c8da23c367) }

var fileDescriptor_04f926c8da23c367 = []byte{
	// 1388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xdf, 0x8e, 0x1b, 0xb5,
	0x17, 0xd6, 0x24, 0x99, 0xec, 0xe4, 0x64, 0x37, 0x59, 0xb9, 0x7f, 0x7e, 0xf3, 0x5b, 0x0a, 0x8a,
	0x46, 0x80, 0x42, 0x5b, 0x2d, 0xd5, 0xb6, 0x12, 0x17, 0xa5, 0xa8, 0xd9, 0x16, 0x35, 0x0b, 0x2d,
	0x8d, 0x9c, 0x55, 0xb9, 0x76, 0x12, 0x93, 0x0c, 0x24, 0x33, 0x61, 0xec, 0x6c, 0x77, 0x91, 0x90,
	0x78, 0x05, 0x04, 0x0f, 0x80, 0xb8, 0xe7, 0x8a, 0x87, 0xe0, 0x29, 0x78, 0x0c, 0xae, 0x41, 0x3e,
	0xf6, 0xcc, 0x78, 0x26, 0xdb, 0x2c, 0x8b, 0x10, 0x82, 0xbb, 0x39, 0x9f, 0x3f, 0xfb, 0xd8, 0xdf,
	0x39, 0x3e, 0xb6, 0x07, 0x76, 0x25, 0x8f, 0x26, 0x3c, 0x59, 0x84, 0x91, 0xdc, 0x5f, 0x26, 0xb1,
	0x8c, 0x89, 0x2b, 0xcf, 0x96, 0x5c, 0xec, 0xed, 0x8e, 0xe6, 0xf1, 0xf8, 0x8b, 0xf1, 0x8c, 0x85,
	0x91, 0x6e, 0x08, 0x5e, 0x87, 0xad, 0x43, 0x85, 0x1d, 0x3d, 0x26, 0x04, 0x6a, 0x33, 0x26, 0x66,
	0xbe, 0xd3, 0x71, 0xba, 0xdb, 0x14, 0xbf, 0x83, 0x0f, 0x80, 0x1c, 0x67, 0x63, 0x1d, 0x86, 0xb2,
	0x97, 0x24, 0xec, 0x4c, 0x31, 0x47, 0xa1, 0x14, 0xc8, 0x74, 0x29, 0x7e, 0x93, 0xab, 0xe0, 0xf2,
	0x39, 0x5f, 0x08, 0xbf, 0xd2, 0xa9, 0x76, 0x6b, 0x54, 0x1b, 0xc1, 0x0f, 0x15, 0xa8, 0xbd, 0x88,
	0x25, 0x27, 0x37, 0x61, 0xf7, 0x84, 0xcd, 0xc3, 0x09, 0x93, 0x71, 0xd2, 0x9b, 0x4c, 0x12, 0x2e,
	0x84, 0x71, 0xb4, 0x86, 0x93, 0xb7, 0xa1, 0x95, 0x61, 0x47, 0xd1, 0x84, 0x9f, 0xfa, 0x15, 0x74,
	0x54, 0x42, 0xc9, 0x75, 0xa8, 0xcf, 0x78, 0x38, 0x9d, 0x49, 0xbf, 0xda, 0x71, 0xba, 0x55, 0x6a,
	0x2c, 0x35, 0x95, 0x24, 0x5e, 0x45, 0x13, 0xbf, 0x86, 0xdd, 0xb4, 0x41, 0x6e, 0x40, 0x43, 0x86,
	0x0b, 0x2e, 0x24, 0x5b, 0x2c, 0x7d, 0x17, 0x3b, 0xe4, 0x80, 0x5a, 0x92, 0x92, 0xc8, 0xaf, 0x77,
	0x9c, 0xee, 0x0e, 0xc5, 0x6f, 0xd2, 0x85, 0xad, 0x91, 0xd6, 0xc6, 0xdf, 0xea, 0x38, 0xdd, 0xe6,
	0x41, 0x6b, 0x1f, 0x65, 0xdc, 0x37, 0x8a, 0xd1, 0xb4, 0x59, 0x8d, 0x2d, 0xc2, 0x69, 0xc4, 0xe4,
	0x2a, 0xe1, 0xbe, 0x87, 0xcb, 0xca, 0x01, 0xd5, 0xba, 0x12, 0xbc, 0x37, 0x9d, 0x0e, 0xc3, 0xa9,
	0xdf, 0xe8, 0x38, 0x5d, 0x8f, 0xe6, 0x40, 0xf0, 0x9d, 0x03, 0xbb, 0xb9, 0xc6, 0x8f, 0xe2, 0xc5,
	0x22, 0x94, 0xb6, 0x6b, 0x67, 0xb3, 0xeb, 0x5b, 0x00, 0xcb, 0x84, 0x8f, 0xb1, 0x9b, 0x16, 0xbf,
	0x79, 0xd0, 0x34, 0x64, 0xa5, 0x3c, 0xb5, 0x9a, 0xd5, 0xb0, 0x6c, 0x3a, 0x55, 0x30, 0x4a, 0x96,
	0x0f, 0xdb, 0xd3, 0x28, 0x4d, 0x9b, 0x83, 0xef, 0x1d, 0xb8, 0x62, 0x45, 0x1e, 0x9d, 0x45, 0x9f,
	0xc5, 0x24, 0x00, 0x57, 0x48, 0x26, 0x39, 0x86, 0xa4, 0x79, 0xb0, 0x6d, 0xfa, 0x0f, 0x15, 0x46,
	0x75, 0x13, 0xb9, 0x05, 0xde, 0x32, 0x89, 0x97, 0xb1, 0x60, 0x73, 0xe3, 0xa6, 0x6d, 0x68, 0x03,
	0x03, 0xd3, 0x8c, 0x40, 0x6e, 0x83, 0x8b, 0x4b, 0xc1, 0x60, 0x35, 0x0f, 0xae, 0x1b, 0x66, 0xc9,
	0x37, 0xd5, 0xa4, 0xe0, 0x53, 0x68, 0xa0, 0x3d, 0x0c, 0xbf, 0xe2, 0x64, 0x0f, 0xbc, 0x05, 0x3b,
	0x3d, 0x3c, 0x93, 0x3c, 0x4d, 0xc5, 0xcc, 0x56, 0xb9, 0xb1, 0x60, 0xa7, 0xc7, 0xa7, 0xc2, 0xe4,
	0x8e, 0xb1, 0x0c, 0xfe, 0x84, 0x89, 0x34, 0x67, 0xb4, 0x15, 0xbc, 0x0f, 0xf5, 0xe3, 0xd3, 0x3f,
	0x39, 0xaa, 0xea, 0x5d, 0x29, 0xf4, 0x7e, 0x00, 0x4d, 0x9c, 0xd6, 0x93, 0x58, 0x88, 0x70, 0x49,
	0xf6, 0x81, 0xe0, 0x74, 0x07, 0x2c, 0x91, 0x6a, 0x4c, 0x7b, 0xb0, 0x73, 0x5a, 0x82, 0x2e, 0xb4,
	0x3e, 0x3c, 0x09, 0x27, 0x3c, 0x1a, 0xf3, 0x01, 0x4b, 0xd8, 0x22, 0x75, 0xd4, 0x9b, 0x72, 0xec,
	0xa5, 0x1d, 0xf5, 0xa6, 0x3c, 0xf8, 0xd5, 0x81, 0xf6, 0xa3, 0x38, 0x12, 0x3c, 0x12, 0x2b, 0x61,
	0xb8, 0xfb, 0xd0, 0x18, 0xa5, 0x9a, 0x98, 0x6c, 0xd9, 0xb5, 0xb3, 0x45, 0xe1, 0x34, 0xa7, 0x90,
	0xb7, 0xa0, 0x2e, 0x71, 0xa9, 0x26, 0x86, 0x3b, 0xa9, 0xe4, 0x08, 0x52, 0xd3, 0x48, 0xee, 0x41,
	0x73, 0x94, 0xaf, 0xc9, 0x04, 0x92, 0xd8, 0x03, 0xeb, 0x16, 0x6a, 0xd3, 0xc8, 0x03, 0x68, 0xf1,
	0xc2, 0x52, 0x4c, 0x5c, 0xaf, 0x99, 0x8e, 0xc5, 0x75, 0xd2, 0x12, 0x39, 0x58, 0x41, 0xe3, 0x45,
	0xba, 0xc9, 0x89, 0x0f, 0x5b, 0xac, 0x50, 0x2a, 0x52, 0x53, 0xc9, 0xb3, 0x5c, 0x8d, 0x3e, 0xe6,
	0x67, 0xb8, 0x84, 0x6d, 0x6a, 0x2c, 0xd2, 0x81, 0xe6, 0x49, 0x2c, 0xc3, 0x68, 0x3a, 0x88, 0x5f,
	0xf2, 0xc4, 0x84, 0xd8, 0x86, 0x54, 0x6d, 0x60, 0xe3, 0xf1, 0x6a, 0x81, 0xd3, 0xaa, 0x52, 0x6d,
	0x04, 0x11, 0x6c, 0x67, 0x6e, 0x87, 0x5c, 0x92, 0x3b, 0x00, 0x59, 0xad, 0x51, 0xce, 0xab, 0x96,
	0xa6, 0x19, 0x91, 0x5a, 0x1c, 0x72, 0x3b, 0xcd, 0x79, 0x9e, 0x18, 0x59, 0xd7, 0xf9, 0x19, 0x23,
	0xf8, 0xad, 0x06, 0x2e, 0x6e, 0x19, 0xb5, 0x46, 0x2c, 0xc7, 0x66, 0xa3, 0x37, 0x68, 0x6a, 0x92,
	0x37, 0x00, 0xe6, 0x4c, 0xc8, 0xbe, 0xae, 0x70, 0x3a, 0xdf, 0x2c, 0x84, 0x74, 0xa1, 0xad, 0x2c,
	0x8c, 0x44, 0xdf, 0x2e, 0x83, 0x65, 0x58, 0xd5, 0xde, 0x0c, 0x3a, 0x8e, 0x25, 0x9b, 0x1f, 0x9f,
	0x9a, 0xe5, 0xaf, 0xe1, 0xe4, 0x0e, 0x34, 0x33, 0xec, 0xe8, 0x31, 0xd6, 0xc9, 0xf5, 0xe2, 0x63,
	0x53, 0xc8, 0x9b, 0xb0, 0x93, 0x8f, 0x12, 0x2e, 0x74, 0x09, 0xad, 0xd2, 0x22, 0x48, 0xee, 0x16,
	0x14, 0xd5, 0xe5, 0xf4, 0x4a, 0x59, 0xa1, 0x21, 0x97, 0x05, 0x51, 0xef, 0x43, 0x4b, 0x8d, 0xf2,
	0x22, 0xef, 0xe8, 0xbd, 0xba, 0x63, 0x89, 0x4a, 0x1e, 0xc2, 0x6b, 0xb9, 0x5a, 0x39, 0xfe, 0x68,
	0xc6, 0xa2, 0x29, 0x9f, 0x60, 0x1d, 0xae, 0xd2, 0x4d, 0x14, 0xf2, 0x10, 0xda, 0xe3, 0xe2, 0x5e,
	0xf3, 0xa1, 0x50, 0xa4, 0x4a, 0x3b, 0x91, 0x96, 0xe9, 0xe4, 0x23, 0xe8, 0xe4, 0x0e, 0x4a, 0xec,
	0x74, 0x22, 0x4d, 0x9c, 0xc8, 0x85, 0xbc, 0x34, 0xde, 0x94, 0x8b, 0xd5, 0x5c, 0x8a, 0xbe, 0x3a,
	0xa9, 0xb7, 0x31, 0xf9, 0xcb, 0x30, 0xee, 0x9b, 0xe5, 0x12, 0x19, 0x3b, 0x66, 0xdf, 0x68, 0x33,
	0xf8, 0xbd, 0x0a, 0xd7, 0x4a, 0x95, 0xb5, 0xcf, 0xd9, 0x84, 0x27, 0x1b, 0xf2, 0x30, 0x3f, 0x65,
	0x2b, 0xe7, 0x9f, 0xb2, 0x3a, 0xeb, 0xcc, 0x29, 0xab, 0xce, 0x51, 0x95, 0x04, 0x3a, 0xbf, 0xf0,
	0x5b, 0x8d, 0x10, 0xad, 0x16, 0xaa, 0x16, 0xeb, 0x63, 0xd7, 0x58, 0xe5, 0x5c, 0xab, 0x5f, 0x9c,
	0x6b, 0x7b, 0xe0, 0x49, 0x9d, 0xa8, 0x3a, 0x87, 0xaa, 0x34, 0xb3, 0xd5, 0xad, 0x41, 0x51, 0xf5,
	0x01, 0x8a, 0x8b, 0xd7, 0x07, 0x71, 0x09, 0x2d, 0xdc, 0x2e, 0xb4, 0x8c, 0x0d, 0xcd, 0x2b, 0xa2,
	0x2a, 0xaf, 0xb3, 0x70, 0x22, 0x0d, 0x90, 0x56, 0x04, 0x6d, 0xad, 0x9b, 0x05, 0xad, 0x2f, 0x11,
	0xaf, 0x00, 0xb6, 0xd3, 0xca, 0xa0, 0xae, 0x40, 0x26, 0x68, 0x05, 0x4c, 0x55, 0xb6, 0x91, 0xb5,
	0xd3, 0x5b, 0xba, 0xb2, 0x59, 0x90, 0x9a, 0xaf, 0xae, 0xf1, 0xfc, 0xcb, 0x95, 0xaa, 0xa8, 0x7e,
	0x5b, 0xef, 0xc3, 0x02, 0x18, 0xfc, 0xe8, 0x40, 0xbb, 0x94, 0x01, 0xe4, 0x9e, 0x8a, 0xb0, 0xca,
	0x02, 0x73, 0x7a, 0xdc, 0x38, 0xff, 0x0c, 0xd6, 0x99, 0x42, 0x0d, 0x97, 0x74, 0xa0, 0x36, 0x61,
	0x92, 0x95, 0x2e, 0x02, 0xfa, 0xb4, 0xc6, 0x16, 0xf2, 0x9e, 0xae, 0x60, 0x5a, 0x7b, 0x73, 0x0e,
	0xfc, 0x6f, 0x6d, 0x6c, 0xdd, 0x4c, 0x2d, 0x6a, 0xf0, 0x4d, 0x05, 0xbc, 0xf4, 0xaa, 0x60, 0xe5,
	0x9f, 0x73, 0x7e, 0xfe, 0x55, 0x5e, 0x79, 0xcb, 0xab, 0x96, 0x6f, 0x79, 0x7b, 0xe0, 0x0d, 0x9e,
	0x3f, 0xa5, 0xd6, 0xe5, 0x30, 0xb3, 0xc9, 0x3e, 0xc0, 0xe0, 0xf9, 0xd3, 0xcd, 0x85, 0xcf, 0x62,
	0x14, 0xef, 0x7c, 0xf5, 0x73, 0xee, 0x7c, 0x28, 0x3c, 0xde, 0xa8, 0xb7, 0x74, 0x6b, 0x06, 0x94,
	0xa3, 0xe9, 0xad, 0x45, 0x33, 0xf8, 0xd9, 0x81, 0xf6, 0x27, 0xfc, 0x25, 0x4e, 0x6d, 0x28, 0xf9,
	0xf2, 0x99, 0x98, 0x5e, 0x52, 0x09, 0x02, 0x35, 0x21, 0xb9, 0x16, 0xc1, 0xa5, 0xf8, 0x4d, 0xee,
	0xc1, 0x35, 0xc1, 0xc7, 0x71, 0x34, 0x11, 0xc3, 0x30, 0x1a, 0xf3, 0xa1, 0x64, 0x89, 0x3c, 0x4e,
	0xb7, 0xab, 0x4b, 0xcf, 0x6f, 0x4c, 0x33, 0xd9, 0x04, 0x0a, 0x3d, 0xb9, 0xc8, 0x2f, 0xc3, 0xc1,
	0x4b, 0xd8, 0xc1, 0x32, 0x8a, 0x1a, 0x5d, 0x7e, 0xca, 0x05, 0xd1, 0xaa, 0x65, 0xd1, 0xf6, 0xc0,
	0x0b, 0x85, 0x95, 0x4c, 0x1e, 0xcd, 0xec, 0xe0, 0x5b, 0x07, 0x5a, 0x69, 0xc6, 0x0c, 0x9e, 0x3f,
	0xdd, 0xe4, 0xfa, 0x26, 0xec, 0x2e, 0x73, 0x26, 0xb5, 0x66, 0xb1, 0x86, 0x93, 0xfb, 0xd0, 0xb4,
	0x30, 0x73, 0x07, 0xfa, 0xff, 0xfa, 0xf6, 0x30, 0x0f, 0x23, 0x6a, 0xb3, 0x83, 0x09, 0x40, 0x9f,
	0x09, 0x75, 0x9b, 0xfe, 0x4b, 0xc1, 0xc3, 0xe7, 0x88, 0x09, 0x1e, 0x3e, 0x47, 0xae, 0x82, 0x1b,
	0xe2, 0x6b, 0xc8, 0x3c, 0x6b, 0xd0, 0x08, 0xbe, 0x86, 0xb6, 0x72, 0x31, 0xe4, 0xf2, 0x19, 0xfb,
	0xfc, 0xe0, 0xee, 0xdf, 0xe3, 0xca, 0x7a, 0x7e, 0xd4, 0x36, 0x3e, 0x3f, 0x82, 0x9f, 0x1c, 0x68,
	0x19, 0xff, 0x87, 0xa1, 0x14, 0xff, 0xb0, 0x7b, 0xf2, 0x2e, 0xb8, 0x27, 0xb1, 0xba, 0x5c, 0xbb,
	0x17, 0x85, 0x46, 0xf3, 0x82, 0x5f, 0x1c, 0x68, 0xf4, 0x39, 0x4b, 0xe4, 0x88, 0x33, 0xf9, 0x2f,
	0x78, 0x95, 0xee, 0x81, 0x27, 0xd2, 0x82, 0xad, 0x37, 0x55, 0x66, 0x6f, 0xae, 0x30, 0xc1, 0x3b,
	0xd0, 0x38, 0x12, 0x7d, 0xce, 0xe6, 0x72, 0x76, 0xa6, 0xa8, 0x61, 0x6a, 0xe0, 0x0a, 0x3c, 0x9a,
	0x03, 0xea, 0x15, 0xbe, 0x65, 0x5e, 0x78, 0x97, 0x5a, 0x72, 0xcf, 0x5a, 0x32, 0xaa, 0x68, 0x8a,
	0xfd, 0x06, 0x99, 0x4b, 0x1d, 0xfe, 0x2b, 0x6f, 0xf4, 0x51, 0x1d, 0x7f, 0x87, 0xdc, 0xfd, 0x23,
	0x00, 0x00, 0xff, 0xff, 0x54, 0x54, 0x13, 0x67, 0x3b, 0x11, 0x00, 0x00,
}
