// Code generated by protoc-gen-go. DO NOT EDIT.
// source: valnode.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types1 "github.com/33cn/chain33/types"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ValNode struct {
	PubKey []byte `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Power  int64  `protobuf:"varint,2,opt,name=power" json:"power,omitempty"`
}

func (m *ValNode) Reset()                    { *m = ValNode{} }
func (m *ValNode) String() string            { return proto.CompactTextString(m) }
func (*ValNode) ProtoMessage()               {}
func (*ValNode) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ValNode) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *ValNode) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type ValNodes struct {
	Nodes []*ValNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *ValNodes) Reset()                    { *m = ValNodes{} }
func (m *ValNodes) String() string            { return proto.CompactTextString(m) }
func (*ValNodes) ProtoMessage()               {}
func (*ValNodes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ValNodes) GetNodes() []*ValNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ValNodeAction struct {
	// Types that are valid to be assigned to Value:
	//	*ValNodeAction_Node
	//	*ValNodeAction_BlockInfo
	Value isValNodeAction_Value `protobuf_oneof:"value"`
	Ty    int32                 `protobuf:"varint,3,opt,name=Ty" json:"Ty,omitempty"`
}

func (m *ValNodeAction) Reset()                    { *m = ValNodeAction{} }
func (m *ValNodeAction) String() string            { return proto.CompactTextString(m) }
func (*ValNodeAction) ProtoMessage()               {}
func (*ValNodeAction) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type isValNodeAction_Value interface {
	isValNodeAction_Value()
}

type ValNodeAction_Node struct {
	Node *ValNode `protobuf:"bytes,1,opt,name=node,oneof"`
}
type ValNodeAction_BlockInfo struct {
	BlockInfo *TendermintBlockInfo `protobuf:"bytes,2,opt,name=blockInfo,oneof"`
}

func (*ValNodeAction_Node) isValNodeAction_Value()      {}
func (*ValNodeAction_BlockInfo) isValNodeAction_Value() {}

func (m *ValNodeAction) GetValue() isValNodeAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValNodeAction) GetNode() *ValNode {
	if x, ok := m.GetValue().(*ValNodeAction_Node); ok {
		return x.Node
	}
	return nil
}

func (m *ValNodeAction) GetBlockInfo() *TendermintBlockInfo {
	if x, ok := m.GetValue().(*ValNodeAction_BlockInfo); ok {
		return x.BlockInfo
	}
	return nil
}

func (m *ValNodeAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ValNodeAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ValNodeAction_OneofMarshaler, _ValNodeAction_OneofUnmarshaler, _ValNodeAction_OneofSizer, []interface{}{
		(*ValNodeAction_Node)(nil),
		(*ValNodeAction_BlockInfo)(nil),
	}
}

func _ValNodeAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ValNodeAction)
	// value
	switch x := m.Value.(type) {
	case *ValNodeAction_Node:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Node); err != nil {
			return err
		}
	case *ValNodeAction_BlockInfo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BlockInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ValNodeAction.Value has unexpected type %T", x)
	}
	return nil
}

func _ValNodeAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ValNodeAction)
	switch tag {
	case 1: // value.node
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ValNode)
		err := b.DecodeMessage(msg)
		m.Value = &ValNodeAction_Node{msg}
		return true, err
	case 2: // value.blockInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TendermintBlockInfo)
		err := b.DecodeMessage(msg)
		m.Value = &ValNodeAction_BlockInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ValNodeAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ValNodeAction)
	// value
	switch x := m.Value.(type) {
	case *ValNodeAction_Node:
		s := proto.Size(x.Node)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ValNodeAction_BlockInfo:
		s := proto.Size(x.BlockInfo)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ReqNodeInfo struct {
	Height int64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
}

func (m *ReqNodeInfo) Reset()                    { *m = ReqNodeInfo{} }
func (m *ReqNodeInfo) String() string            { return proto.CompactTextString(m) }
func (*ReqNodeInfo) ProtoMessage()               {}
func (*ReqNodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ReqNodeInfo) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ReqBlockInfo struct {
	Height int64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
}

func (m *ReqBlockInfo) Reset()                    { *m = ReqBlockInfo{} }
func (m *ReqBlockInfo) String() string            { return proto.CompactTextString(m) }
func (*ReqBlockInfo) ProtoMessage()               {}
func (*ReqBlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ReqBlockInfo) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*ValNode)(nil), "types.ValNode")
	proto.RegisterType((*ValNodes)(nil), "types.ValNodes")
	proto.RegisterType((*ValNodeAction)(nil), "types.ValNodeAction")
	proto.RegisterType((*ReqNodeInfo)(nil), "types.ReqNodeInfo")
	proto.RegisterType((*ReqBlockInfo)(nil), "types.ReqBlockInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Valnode service

type ValnodeClient interface {
	IsSync(ctx context.Context, in *types1.ReqNil, opts ...grpc.CallOption) (*IsHealthy, error)
}

type valnodeClient struct {
	cc *grpc.ClientConn
}

func NewValnodeClient(cc *grpc.ClientConn) ValnodeClient {
	return &valnodeClient{cc}
}

func (c *valnodeClient) IsSync(ctx context.Context, in *types1.ReqNil, opts ...grpc.CallOption) (*IsHealthy, error) {
	out := new(IsHealthy)
	err := grpc.Invoke(ctx, "/types.valnode/IsSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Valnode service

type ValnodeServer interface {
	IsSync(context.Context, *types1.ReqNil) (*IsHealthy, error)
}

func RegisterValnodeServer(s *grpc.Server, srv ValnodeServer) {
	s.RegisterService(&_Valnode_serviceDesc, srv)
}

func _Valnode_IsSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types1.ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValnodeServer).IsSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.valnode/IsSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValnodeServer).IsSync(ctx, req.(*types1.ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

var _Valnode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.valnode",
	HandlerType: (*ValnodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsSync",
			Handler:    _Valnode_IsSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "valnode.proto",
}

func init() { proto.RegisterFile("valnode.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xdf, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0x97, 0xf5, 0xdb, 0xee, 0xeb, 0xdd, 0x0f, 0x46, 0x90, 0x51, 0xfa, 0x54, 0xc2, 0x94,
	0x82, 0x30, 0x64, 0x82, 0x82, 0x6f, 0xee, 0x69, 0x43, 0xf0, 0x21, 0x0e, 0xdf, 0xbb, 0xee, 0xea,
	0x8a, 0x69, 0xd2, 0xb5, 0xd9, 0x24, 0xff, 0x82, 0x7f, 0xb5, 0x34, 0x8d, 0xf3, 0x41, 0x7c, 0x3c,
	0xf7, 0x9c, 0x9b, 0xcf, 0x49, 0x02, 0xc3, 0x63, 0x2a, 0xa4, 0xda, 0xe2, 0xac, 0xac, 0x94, 0x56,
	0xd4, 0xd7, 0xa6, 0xc4, 0x3a, 0x1a, 0x64, 0xaa, 0x28, 0x94, 0x6c, 0x87, 0xd1, 0x58, 0xa3, 0xdc,
	0x62, 0x55, 0xe4, 0x52, 0xb7, 0x13, 0x76, 0x07, 0xbd, 0x97, 0x54, 0x3c, 0xa9, 0x2d, 0xd2, 0x09,
	0x04, 0xe5, 0x61, 0xf3, 0x88, 0x26, 0x24, 0x31, 0x49, 0x06, 0xdc, 0x29, 0x7a, 0x0e, 0x7e, 0xa9,
	0x3e, 0xb0, 0x0a, 0xbb, 0x31, 0x49, 0x3c, 0xde, 0x0a, 0x76, 0x0d, 0xff, 0xdd, 0x62, 0x4d, 0xa7,
	0xe0, 0x37, 0xe4, 0x3a, 0x24, 0xb1, 0x97, 0xf4, 0xe7, 0xa3, 0x99, 0x65, 0xcf, 0x9c, 0xcf, 0x5b,
	0x93, 0x7d, 0x12, 0x18, 0xba, 0xd1, 0x43, 0xa6, 0x73, 0x25, 0xe9, 0x14, 0xfe, 0x35, 0x96, 0xe5,
	0xfd, 0x5a, 0x5b, 0x76, 0xb8, 0x75, 0xe9, 0x3d, 0x9c, 0x6d, 0x84, 0xca, 0xde, 0x57, 0xf2, 0x55,
	0xd9, 0x0e, 0xfd, 0x79, 0xe4, 0xa2, 0xeb, 0xd3, 0x75, 0x16, 0xdf, 0x89, 0x65, 0x87, 0xff, 0xc4,
	0xe9, 0x08, 0xba, 0x6b, 0x13, 0x7a, 0x31, 0x49, 0x7c, 0xde, 0x5d, 0x9b, 0x45, 0x0f, 0xfc, 0x63,
	0x2a, 0x0e, 0xc8, 0x2e, 0xa0, 0xcf, 0x71, 0xdf, 0x70, 0x6c, 0x6e, 0x02, 0xc1, 0x0e, 0xf3, 0xb7,
	0x9d, 0xb6, 0x5d, 0x3c, 0xee, 0x14, 0xbb, 0x84, 0x01, 0xc7, 0xfd, 0xe9, 0xf0, 0xbf, 0x72, 0xf3,
	0x5b, 0xe8, 0xb9, 0xe7, 0xa7, 0x57, 0x10, 0xac, 0xea, 0x67, 0x23, 0x33, 0x3a, 0x74, 0x2d, 0x1b,
	0x50, 0x2e, 0xa2, 0xb1, 0x93, 0xab, 0x7a, 0x89, 0xa9, 0xd0, 0x3b, 0xc3, 0x3a, 0x9b, 0xc0, 0xfe,
	0xc2, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x71, 0x98, 0xe3, 0xbd, 0x01, 0x00, 0x00,
}
